<a href="https://colab.research.google.com/github/rijosasidharlearning-jpg/DataScienceLab1/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# Install rclone
!curl https://rclone.org/install.sh | sudo bash

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4734  100  4734    0     0   5622      0 --:--:-- --:--:-- --:--:--  5629
Archive:  rclone-current-linux-amd64.zip
   creating: tmp_unzip_dir_for_rclone/rclone-v1.74.4-linux-amd64/
  inflating: tmp_unzip_dir_for_rclone/rclone-v1.74.4-linux-amd64/rclone.1  [text]
  inflating: tmp_unzip_dir_for_rclone/rclone-v1.74.4-linux-amd64/git-log.txt  [text]
  inflating: tmp_unzip_dir_for_rclone/rclone-v1.74.4-linux-amd64/README.txt  [text]
  inflating: tmp_unzip_dir_for_rclone/rclone-v1.74.4-linux-amd64/rclone  [binary]
  inflating: tmp_unzip_dir_for_rclone/rclone-v1.74.4-linux-amd64/README.html  [text]
Purging old database entries in /usr/share/man...
Processing manual pages under /usr/share/man...
Purging old database entries in /usr/share/man/it...
Processing manual pages under /usr/share/man/it...
Purging old database entries in /usr/share/man/pl...
Processing manual pages under /usr/share/man/pl...
Purging old database entries in /usr/share/man/ja...
Processing manual pages under /usr/share/man/ja...
Purging old database entries in /usr/share/man/fr...
Processing manual pages under /usr/share/man/fr...
Purging old database entries in /usr/share/man/zh_CN...
Processing manual pages under /usr/share/man/zh_CN...
Purging old database entries in /usr/share/man/sv...
Processing manual pages under /usr/share/man/sv...
Purging old database entries in /usr/share/man/es...
Processing manual pages under /usr/share/man/es...
Purging old database entries in /usr/share/man/da...
Processing manual pages under /usr/share/man/da...
Purging old database entries in /usr/share/man/zh_TW...
Processing manual pages under /usr/share/man/zh_TW...
Purging old database entries in /usr/share/man/sl...
Processing manual pages under /usr/share/man/sl...
Purging old database entries in /usr/share/man/pt_BR...
Processing manual pages under /usr/share/man/pt_BR...
Purging old database entries in /usr/share/man/pt...
Processing manual pages under /usr/share/man/pt...
Purging old database entries in /usr/share/man/id...
Processing manual pages under /usr/share/man/id...
Purging old database entries in /usr/share/man/tr...
Processing manual pages under /usr/share/man/tr...
Purging old database entries in /usr/share/man/de...
Processing manual pages under /usr/share/man/de...
Purging old database entries in /usr/share/man/nl...
Processing manual pages under /usr/share/man/nl...
Purging old database entries in /usr/share/man/ko...
Processing manual pages under /usr/share/man/ko...
Purging old database entries in /usr/share/man/cs...
Processing manual pages under /usr/share/man/cs...
Purging old database entries in /usr/share/man/hu...
Processing manual pages under /usr/share/man/hu...
Purging old database entries in /usr/share/man/ru...
Processing manual pages under /usr/share/man/ru...
Purging old database entries in /usr/share/man/ro...
Processing manual pages under /usr/share/man/ro...
Purging old database entries in /usr/share/man/uk...
Processing manual pages under /usr/share/man/uk...
Purging old database entries in /usr/share/man/sr...
Processing manual pages under /usr/share/man/sr...
Processing manual pages under /usr/local/man...
mandb: can't update index cache /var/cache/man/oldlocal/3476: No such file or directory
Updating index cache for path `/usr/local/man/man1'. Wait...done.
Checking for stray cats under /usr/local/man...
Checking for stray cats under /var/cache/man/oldlocal...
1 man subdirectory contained newer manual pages.
5 manual pages were added.
0 stray cats were added.
18 old database entries were purged.

rclone v1.74.4 has successfully installed.
Now run "rclone config" for setup. Check https://rclone.org/docs/ for more details.

### Fallback: Manual Drive ID entry
If the above command fails or you already have your Drive ID from a local `rclone config` setup, paste it below.

In [9]:
import os

# 1. YOUR TOKEN (already updated in previous step)
FINAL_TOKEN = '{"access_token":"EwB4BMl6BAAU9BatlgMxts2T1B5e3Mucgfs4jcAAASOyQ/pmyRZagG2RDmApPSRIlUvDUaUufY8EwkZAMcFbd/2GM5kX41qqJaGyI1hnMBa2WBXCr7h916qZqez0oIH1fxNEhf9mpaJAQGuEOcXARkDdRnkqvsifmOOy5otGK8LWfQaIrvrJoAIwZQ+fQjdDZPHdr2Sl2Is7hNwO5XWSRHLgOajg7lXRw+004S1cDgoFzava8qPQuE+PS5cBb76MjeieYgHnkyeY0KAnAN7cHCwoV0j0mf/MnDcsHPAwEbf+aGX6rK3K+I1fHzsTS6OVwlQDYT6VVpcxSdWS1FpObqiEY7ipSMeFhsU6D+gfmfOlxKeXyQuDZJx6+R2DuUAQZgAAEKNNxWVXSjbYDUmaXYbrCpZAA0MtkPPk4EWyRC+QezbD8i+RHaEbTkFy5khb36oW1jKl2RPCzxY8R5UrbHRLh9CSBY80QhwezHG3R8FOxGxyTwCIn5QeAabhA1eoIJVSqvHXwZZX15FSZZk+zDRtdznqzDghv69iVe0DMRd9WYP4DE+MQUhVtuZekLxy7BR51Cjy0wbWNXwGFyE1Z4Kfr+mvj/c2Tbi8OLkr+jTMP2tb04VuvEp5SUQH7fcMpLhMX/ksTMkyOYAq64WNiCeoY1i4GeK82NzXk/jF5F3fAZtHXvVybmc7zj6Q37XM9SjqL2Ig9eiNt+t/QD505WbFSLTAvEyLm/1tGPUfTqPsZk2k3iVw/IYAdiKiLbZoNm3PunSn8gojuOqklz4M+CQiq64VaFz9qqZXggqqpiq5noHmIlg63lRwHtOYuiT3lQr1VDRbeQc1i8qy9uSXsnRBa7aKngQUQy7ai8QQyRRQgRO0on8nGSfIFbY5+miHdjDYZj0tUPjfv+UNqVnM2n6GPNvNDoOyoiDO0MOwok/hWo1mZkwL9QZ/Nk7KVfRXk8PkD7azdvO1j0Qsv7uV+9SNzVkEOfeJzIcW96WSwb9Uyvcp23HxDlIVxfBl9oqATJe8onqWDtSBBy5OeuA2RcoCgHshX6V8wyegxqDbXNLdC0qGScl9fRHK/ljHkZBC/s2C6lCn1qdJgyOd+QomJ9CxCbrcmd4mrUYeLQZFAZDJfHSn7c+W+7jQluIEgVXJ31B4hBcuosCwj3MOy7+EF5yTxpYhJiREM37BJcbctBF2lJWDjt6SXr3IPQVtcyfmILN3xpqiQujUTRtHbaz9a9gvXkdRQk9ffM4gv7sDKhFY/octYfyvSAyzBzw1L0U0EWrmL2RDo9vR7V0grVME2CNxp9n12vxcCGoeoB63HUqzOPVZHhiU2Qc+/Ilc5NNFxZJ01qIEbp9RRO2X2BDJZDG4DYDmwoVKGg9V7Z9DAUmVcX4qmjB4WLHMLfzeSBxtplaD6F+mnjbI2aliYg6BQ9vB8++fUYrqXri/UPPAsZSIyC7uIGhY+6WMK1Z0OxMGODeCXxLppXL3+YJ61ieMkbLpTuAI1C1fxdlPbLXYvth7cOivmN9qAw==","token_type":"Bearer","refresh_token":"M.C561_BAY.0.U.MsaArtifacts.-Cl5ZIpFQV!fSI1I3ce2ylVV02EMwHExrSqVUWejV1i*u*W1G49i!4jaxQeBOXtUMDVwgDYHO76njRFYsvbeADzEip1Xo*3N3l4AXIrC71ndVZhScOOizTo*0hmh0O3V5Jt9i*16xWnNXFlgqwMB8hCgSz!tH3XHp!ZHG95B1pR2OlaEiUKK!Pqp*Uu5KbOx90wAg*!184LLPajhFtNkQsD8Bz7dryp5IncjY0cSwaosUsubcMT4RJ8JZBs9z7l*32zK4P*cCpJDRXT9nQcdGQryHBmPPxvd2ricTtH8WyQ1s*iUdsTDQ8tH8lnTjIpgl1HddlG6GNNCzGzAavuMrc2b0VqM88GLhcTZK9rT*FHoAJ92Rj*fcdUfpGPH5d3tgZndDWS*n4YadoAa!3iCb5RlC2mbDPiU*2LzEnkvoYCd5BnsouVGFBp9WzSgqK1*lZQ$$","expiry":"2026-07-10T14:23:37.8254653+05:30","expires_in":3599}'

# 2. IDENTIFIED DRIVE ID
FINAL_DRIVE_ID = '620C6EC4436134C1'

conf_path = "/root/.config/rclone/rclone.conf"
!mkdir -p /root/.config/rclone/

config_text = f"""[onedrive]
type = onedrive
token = {FINAL_TOKEN.strip()}
drive_id = {FINAL_DRIVE_ID.strip()}
drive_type = personal

[restricted]
type = alias
remote = onedrive:Colab/Edureka
"""

with open(conf_path, "w") as f:
    f.write(config_text)

print("✅ Configuration LOCKED IN.")
print("Now run cell d6a4d15a to mount.")

✅ Configuration LOCKED IN.
Now run cell d6a4d15a to mount.

### 🔄 Future Syncing
Run this cell whenever you want to pull the latest version of your files from OneDrive to Colab.

In [10]:
# 1. Sync the specific folder to Colab's local storage
!rclone copy restricted: /content/onedrive_data -P

# 2. List files to verify
import os
if os.path.exists('/content/onedrive_data/Students.csv'):
    print("✅ Sync Complete. Files available in /content/onedrive_data/")
    !ls /content/onedrive_data
else:
    print("❌ Sync failed. Check your internet connection or rclone config.")

✅ Sync Complete. Files available in /content/onedrive_data/
Students.csv

# Pandas Series (has explicit indexing and labels)
##Can create it rom series, list np arrays

In [4]:
import pandas as pd;
import numpy as np;

s1 = pd.Series([1,2,3,4,5])
print("from list ",s1, " type ", s1.dtype, " Classtype ", type(np.setdiff1d))

s2 = pd.Series();
print("from pd series",s2, " type ", s2.dtype, " Classtype ", type(s2))

s3 = pd.Series(np.array([1,2,3,4,5]))
print("from np array ",s3, " type ", s3.dtype, " Classtype ", type(s3))

from list  0    1
1    2
2    3
3    4
4    5
dtype: int64  type  int64  Classtype  <class 'numpy._ArrayFunctionDispatcher'>
from pd series Series([], dtype: object)  type  object  Classtype  <class 'pandas.core.series.Series'>
from np array  0    1
1    2
2    3
3    4
4    5
dtype: int64  type  int64  Classtype  <class 'pandas.core.series.Series'>

## create series from dictionary

In [6]:
ds1 = pd.Series({'Name':1,'Age':2,'Humanity':3,'Strength':4,'Intelligence':5})
print(ds1)

Name            1
Age             2
Humanity        3
Strength        4
Intelligence    5
dtype: int64

In [10]:
print(ds1.iloc[4])
ds1.iloc[4]

5

np.int64(5)

In [11]:
print(ds1.loc["Name"])

1

In [13]:
print(ds1.iloc[0:4])

Name        1
Age         2
Humanity    3
Strength    4
dtype: int64

In [14]:
print(ds1.loc["Name":"Strength"])

Name        1
Age         2
Humanity    3
Strength    4
dtype: int64

#Negative indexing for list (last index will be -1, second last -2 so on)

In [15]:
list1 =[1,2,4,5,67]
print(list1[-1])

67

#Filter and SubSet

In [5]:
#filter

fs1 = pd.Series([1,2,345,435,35,67,678,8,150,78,878,2323,2,45])

print(" greater than 100 ", fs1>100)
print(" greater than 100 and less than 200 ", fs1[(fs1>100) & (fs1<=200)])
save = fs1[fs1>100]
print(" greater than 100 ", save)
save.reset_index(drop=True)
print(" greater than 100 , without inplace or re assign ", save)
save.reset_index(drop=True, inplace=True)
print(" greater than 100 with inplace ", save)

 greater than 100  0     False
1     False
2      True
3      True
4     False
5     False
6      True
7     False
8      True
9     False
10     True
11     True
12    False
13    False
dtype: bool
 greater than 100 and less than 200  8    150
dtype: int64
 greater than 100  2      345
3      435
6      678
8      150
10     878
11    2323
dtype: int64
 greater than 100 , without inplace or re assign  2      345
3      435
6      678
8      150
10     878
11    2323
dtype: int64
 greater than 100 with inplace  0     345
1     435
2     678
3     150
4     878
5    2323
dtype: int64

In [ ]:
print(sum(fs1))

#DataFrames

In [11]:
import os
import pandas as pd

# 1. Ensure the directory exists
!mkdir -p /content/onedrive_data

# 2. Move the file from /content to /content/onedrive_data if it exists at the root
if os.path.exists('/content/Students.csv'):
    !mv /content/Students.csv /content/onedrive_data/Students.csv
    print("✅ Moved Students.csv to /content/onedrive_data/")

# 3. Update the DataFrame to use the new path
file_path = '/content/onedrive_data/Students.csv'
if os.path.exists(file_path):
    df_students = pd.read_csv(file_path)
    print("✅ DataFrame updated to load from: /content/onedrive_data/Students.csv")
    display(df_students.head())
else:
    print("❌ File not found in /content/onedrive_data/. Run the 'Future Syncing' cell above to pull it from OneDrive.")

✅ DataFrame updated to load from: /content/onedrive_data/Students.csv

   Unnamed: 0  StudentId StudentName  Age    Subject  Class
0           0          1         Raj   17      Maths      1
1           1          2         Ram   17    Physics      2
2           2          3      Raghav   17  Chemistry      3
3           3          4        Jeff   16  Geography      3
4           4          5       Joffy   17      Civis      4

In [15]:
df_students.tail(7)

   Unnamed: 0  StudentId StudentName  Age    Subject  Class
3           3          4        Jeff   16  Geography      3
4           4          5       Joffy   17      Civis      4
5           5          6      Nithin   17    Biology      3
6           6          7      Roshan   16      Civis      1
7           7          8       Thoma   17  Geography      2
8           8          9        Anil   18      Maths      4
9           9         10         Aju   17  Chemistry      1

In [17]:
df_students[["StudentId"]]

   StudentId
0          1
1          2
2          3
3          4
4          5
5          6
6          7
7          8
8          9
9         10

In [21]:
df_students.columns

print("df", type(df_students))
print("df", type(df_students[["StudentId"]]))
print("df", type(df_students["StudentId"]))

df <class 'pandas.core.frame.DataFrame'>
df <class 'pandas.core.frame.DataFrame'>
df <class 'pandas.core.series.Series'>

In [23]:
df_students[df_students["Class"]>3]

   Unnamed: 0  StudentId StudentName  Age Subject  Class
4           4          5       Joffy   17   Civis      4
8           8          9        Anil   18   Maths      4

In [24]:
df_students["Class"]>3

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8     True
9    False
Name: Class, dtype: bool

In [26]:
df_students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   10 non-null     int64
 1   StudentId    10 non-null     int64
 2   StudentName  10 non-null     object
 3   Age          10 non-null     int64
 4   Subject      10 non-null     object
 5   Class        10 non-null     int64
dtypes: int64(4), object(2)
memory usage: 612.0+ bytes

In [27]:
df_students.describe()

       Unnamed: 0  StudentId        Age      Class
count    10.00000   10.00000  10.000000  10.000000
mean      4.50000    5.50000  16.900000   2.400000
std       3.02765    3.02765   0.567646   1.173788
min       0.00000    1.00000  16.000000   1.000000
25%       2.25000    3.25000  17.000000   1.250000
50%       4.50000    5.50000  17.000000   2.500000
75%       6.75000    7.75000  17.000000   3.000000
max       9.00000   10.00000  18.000000   4.000000

In [33]:
df_students["Fess"] =df_students["Class"]*3
display(df_students)

   Unnamed: 0  StudentId StudentName  Age    Subject  Class  Fess
0           0          1         Raj   17      Maths      1     3
1           1          2         Ram   17    Physics      2     6
2           2          3      Raghav   17  Chemistry      3     9
3           3          4        Jeff   16  Geography      3     9
4           4          5       Joffy   17      Civis      4    12
5           5          6      Nithin   17    Biology      3     9
6           6          7      Roshan   16      Civis      1     3
7           7          8       Thoma   17  Geography      2     6
8           8          9        Anil   18      Maths      4    12
9           9         10         Aju   17  Chemistry      1     3

In [35]:
df_students[df_students["Fess"]>=10]

   Unnamed: 0  StudentId StudentName  Age Subject  Class  Fess
4           4          5       Joffy   17   Civis      4    12
8           8          9        Anil   18   Maths      4    12

In [36]:
# list to frames

lst = [1,2,3,4,5,6]
pd = pd.DataFrame(lst)
print(pd)

   0
0  1
1  2
2  3
3  4
4  5
5  6

In [39]:
pd.columns = ["Col1"]
print(pd)

   Col1
0     1
1     2
2     3
3     4
4     5
5     6

##data frames from list of dictionary

In [47]:
import pandas as pd

lstDic = [{"a":100,"b":90,"c":50},{"a":60,"b":80,"c":100},{"a":60,"b":80,"d":100}]
# Renaming the result to pd1 and ensuring we use the pandas module correctly
pd1 = pd.DataFrame(lstDic)
print(pd1)

     a   b      c      d
0  100  90   50.0    NaN
1   60  80  100.0    NaN
2   60  80    NaN  100.0

In [48]:
pd1.rename(columns={"a":"x","b":"y","c":"z"}, inplace=True)
print(pd1)

     x   y      z      d
0  100  90   50.0    NaN
1   60  80  100.0    NaN
2   60  80    NaN  100.0

In [53]:
# Re-creating the DataFrame to ensure pd1 is a DataFrame object and not a list
pd1 = pd.DataFrame(lstDic)

# Now we can safely assign the new column names
pd1.columns = ["A", "B", "C", "D"]
print(pd1)

     A   B      C      D
0  100  90   50.0    NaN
1   60  80  100.0    NaN
2   60  80    NaN  100.0

In [55]:
pd1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       2 non-null      float64
 3   D       1 non-null      float64
dtypes: float64(2), int64(2)
memory usage: 228.0 bytes

In [57]:
pd1[pd1["D"].isna()]
pd1[pd1["C"].isna()]

    A   B   C      D
2  60  80 NaN  100.0

In [58]:
# Changing Index

lstdic1 = [{"a":100,"b":90},{"a":80,"b":90}]
pd2 = pd.DataFrame(lstdic1,index=["First", "Second"])
print(pd2)

          a   b
First   100  90
Second   80  90

In [63]:
# Use .loc to access a row by its index name
print("Accessing row by label using .loc:")
print(pd2.loc["First"])

# If you wanted the column 'a', you would use:
# print(pd2["a"])

Accessing row by label using .loc:
a    100
b     90
Name: First, dtype: int64

### Using `.iloc` for Integer-based Indexing
Unlike `.loc` which uses labels, `.iloc` uses the integer position.

In [64]:
# Access the first row (position 0)
print("First row using iloc:")
display(pd2.iloc[0])

# Access the first element of the first row (row 0, column 0)
print("\nElement at [0,0]:", pd2.iloc[0, 0])

# Access all rows for the second column (position 1)
print("\nSecond column using iloc:")
display(pd2.iloc[:, 1])

First row using iloc:

a    100
b     90
Name: First, dtype: int64

Element at [0,0]: 100

Second column using iloc:

First     90
Second    90
Name: b, dtype: int64

In [65]:
display(pd1)

     A   B      C      D
0  100  90   50.0    NaN
1   60  80  100.0    NaN
2   60  80    NaN  100.0

In [66]:
pd1["D"] = pd1["D"].fillna(pd1["D"].mean())
display(pd1)

     A   B      C      D
0  100  90   50.0  100.0
1   60  80  100.0  100.0
2   60  80    NaN  100.0

In [68]:
pd1["Discount"] =10;
display(pd1)

     A   B      C      D  Discount
0  100  90   50.0  100.0        10
1   60  80  100.0  100.0        10
2   60  80    NaN  100.0        10

In [70]:
pd1.loc[0]

A           100.0
B            90.0
C            50.0
D           100.0
Discount     10.0
Name: 0, dtype: float64

##Concat

In [71]:
pd3 = pd.DataFrame({"ID":[1,2,3,4],"Name":["A","B","C","D"]})
pd4 = pd.DataFrame({"ID":[5,6,7,8],"Name":["E","F","G","H"]})
display(pd3)
display(pd4)

   ID Name
0   1    A
1   2    B
2   3    C
3   4    D

   ID Name
0   5    E
1   6    F
2   7    G
3   8    H

In [72]:
#vertical axis = 0
pd5 = pd.concat([pd3,pd4],axis=0)
display(pd5)

   ID Name
0   1    A
1   2    B
2   3    C
3   4    D
0   5    E
1   6    F
2   7    G
3   8    H

In [73]:
# horizontal axis =1
pd6 = pd.concat([pd3,pd4],axis=1)
display(pd6)

   ID Name  ID Name
0   1    A   5    E
1   2    B   6    F
2   3    C   7    G
3   4    D   8    H